# Generated by Django 3.0 on 2022-03-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table1',
            new_name='Person',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
